name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 9-addbadges_sqllint
  pull_request:
    branches:
      - main
      - dev

jobs:
  recce_sqlfluff:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Choose a version compatible with dbt Core

      # Install dbt Core and dependencies
      - name: Install dbt
        run: |
          pip install dbt-bigquery > /dev/null # > /dev/null 2>&1 will hide even errors
          dbt --version > /dev/null

      # Create profiles.yml
      - name: Configure dbt profiles
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          mkdir -p ~/.dbt
          echo "$GCP_CREDENTIALS" > ~/service-account-key.json
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_pizza:
            target: dev
            outputs:
              dev:
                dataset: pizza
                job_execution_timeout_seconds: 150
                job_retries: 1
                location: northamerica-northeast1
                method: service-account
                priority: interactive
                project: pocloadaccount
                threads: 4
                type: bigquery
                keyfile: /home/runner/service-account-key.json
          EOF

      - name: Install SQLFluff
        run: pip install sqlfluff sqlfluff-templater-dbt > /dev/null


      - name: Run SQLFluff linting
        run: sqlfluff lint -v ./proj_dbt/dbt_pizza/models/ > sqlfluff_report.txt || true
        env:
          DBT_PROFILES_DIR: /home/runner/.dbt
          DBT_PROJECT_DIR: /home/runner/work/bigquery_dwh/bigquery_dwh/proj_dbt/dbt_pizza
        continue-on-error: true

      - name: Voilation Count and Badge Update in SQLFluff
        run: |
          VIOLATION_COUNT=$(grep -A 1 '==== summary ====' sqlfluff_report.txt | grep -oP 'violations:\s+\K\d+')
          echo "SQLFluff Violations: $VIOLATION_COUNT"
          # Remove existing SQLFluff badge
          sed -i '/!\[sqlfluff\]/d' README.md
          # Create a new README with the badge prepended
          echo -e "![sqlfluff](https://img.shields.io/badge/sql%20violations-$VIOLATION_COUNT-red)\n$(cat README.md)" > README.md.tmp
          # Replace the original README with the updated one
          mv README.md.tmp README.md

      - name: Commit and Push README update 
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md sqlfluff_report.txt
          git commit -m "Update SQLFluff badge in README [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}

      - name: Install Recce
        run: |
          pip install --upgrade pip > /dev/null
          pip install packaging recce agate > /dev/null

      - name: Run dbt compilation (required for Recce)
        run: dbt compile
        working-directory: ./proj_dbt/dbt_pizza
        env:
          DBT_PROFILES_DIR: /home/runner/.dbt
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/service-account-key.json


      - name: Run Recce validation
        run: |
          GOOGLE_APPLICATION_CREDENTIALS=/home/runner/service-account-key.json \
          recce run --profiles-dir /home/runner/.dbt --output recce-state.json
        working-directory: /home/runner/work/bigquery_dwh/bigquery_dwh/proj_dbt/dbt_pizza
        env:
          DBT_PROFILES_DIR: /home/runner/.dbt
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/service-account-key.json

      - name: Generate Recce summary
        run: |
          GOOGLE_APPLICATION_CREDENTIALS=/home/runner/service-account-key.json \
          recce summary recce-state.json
        working-directory: /home/runner/work/bigquery_dwh/bigquery_dwh/proj_dbt/dbt_pizza
        env:
          DBT_PROFILES_DIR: /home/runner/.dbt
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/service-account-key.json