name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - 7-integrate-piperider
  pull_request:
    branches:
      - main
      - dev

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Choose a version compatible with dbt Core

      # Install dbt Core and dependencies
      - name: Install dbt
        run: |
          pip install dbt-bigquery 
          dbt --version

      # Create profiles.yml
      - name: Configure dbt profiles
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          mkdir -p ~/.dbt
          echo "$GCP_CREDENTIALS" > ~/service-account-key.json
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_pizza:
            target: dev
            outputs:
              dev:
                dataset: pizza
                job_execution_timeout_seconds: 150
                job_retries: 1
                location: northamerica-northeast1
                method: service-account
                priority: interactive
                project: pocloadaccount
                threads: 4
                type: bigquery
                keyfile: ~/service-account-key.json
          EOF

      # Install dbt dependencies
      - name: Install dbt dependencies
        run: dbt deps
        working-directory: ./proj_dbt/dbt_pizza # Adjust if dbt_project is in a subdirectory

      # Run dbt tests
      - name: Run dbt tests
        run: dbt test
        working-directory: ./proj_dbt/dbt_pizza

      # Run dbt build (combines run + test + compile)
      - name: Run dbt build
        run: dbt build
        working-directory: ./proj_dbt/dbt_pizza
        env:
          DBT_PROFILES_DIR: ~/.dbt