name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - 7-integrate-piperider
  pull_request:
    branches:
      - main
      - dev

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Choose a version compatible with dbt Core

      # Install dbt Core and dependencies
      - name: Install dbt
        run: |
          pip install dbt-bigquery 
          dbt --version

      # Create profiles.yml
      - name: Configure dbt profiles
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          mkdir -p ~/.dbt
          echo "$GCP_CREDENTIALS" > ~/service-account-key.json
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_pizza:
            target: dev
            outputs:
              dev:
                dataset: pizza
                job_execution_timeout_seconds: 150
                job_retries: 1
                location: northamerica-northeast1
                method: service-account
                priority: interactive
                project: pocloadaccount
                threads: 4
                type: bigquery
                keyfile: ~/service-account-key.json
          EOF

      - name: Verify keyfile and profiles.yml
        run: |
                echo "Checking keyfile and profiles.yml..."
                ls -la ~/service-account-key.json ~/.dbt/profiles.yml
                if [ -f ~/service-account-key.json ]; then
                  echo "Keyfile exists"
                else
                  echo "Keyfile not found"
                  exit 1
                fi
                if [ -f ~/.dbt/profiles.yml ]; then
                  echo "profiles.yml exists"
                  cat ~/.dbt/profiles.yml
                else
                  echo "profiles.yml not found"
                  exit 1
                fi

      - name: Debug keyfile
        run: |
          ls -la ~/service-account-key.json
          cat ~/service-account-key.json
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      # Run dbt debug to test configuration
      - name: Run dbt debug
        run: dbt debug
        working-directory: ./proj_dbt/dbt_pizza
        env:
          DBT_PROFILES_DIR: /home/runner/.dbt
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/service-account-key.json


      # # Install dbt dependencies
      # - name: Install dbt dependencies
      #   run: dbt deps
      #   working-directory: ./proj_dbt/dbt_pizza # Adjust if dbt_project is in a subdirectory

      # - name: Run dbt tests
      #   run: dbt test
      #   working-directory: ./proj_dbt/dbt_pizza
      #   env:
      #     DBT_PROFILES_DIR: ~/.dbt
      #     GOOGLE_APPLICATION_CREDENTIALS: ~/service-account-key.json

      # # Run dbt build (combines run + test + compile)
      # - name: Run dbt build
      #   run: dbt build
      #   working-directory: ./proj_dbt/dbt_pizza
      #   env:
      #     DBT_PROFILES_DIR: ~/.dbt